### ISSUE TITLE
Latest Version fails with Error if Browser request "browserify.js"

### ISSUE THREAD

**Issue by haeferer** [joeferner/redis-commander#232]
thx for your great work, but right now the CommandLine Interface, does not work 

```
http://redisc:8088/browserify.js
```

Answer from Server 
```
Error: Cannot find module 'cmdparser' from '/'
   at /src/redis-commander/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
   at process (/src/redis-commander/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
   at ondir (/src/redis-commander/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
   at load (/src/redis-commander/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
   at onex (/src/redis-commander/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
   at /src/redis-commander/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
   at FSReqWrap.oncomplete (fs.js:152:21)
```

**Comment by Ajnasz** [comment]
With git bisect, I got the following result:

```
db1713a5f92cfc72abe2dbacabe05a888f34b384 is the first bad commit
commit db1713a5f92cfc72abe2dbacabe05a888f34b384
Author: Oren Zomer <oren.zomer@gmail.com>
Date:   Sun Jan 7 21:22:59 2018 +0200

    do not change dir

:040000 040000 5547b8e972eb6483e04ace4adff2b77d40023e46 da45f44c43e6e887057606911dad48afde38c28a M      lib
```

**Comment by daniel-cohen** [comment]
Getting the same error as @haeferer with the latest docker image.

**Comment by sooslaca** [comment]
+1

**Comment by felipe-vvoosh** [comment]
+1

**Comment by sseide** [comment]
works without problem with latest version from gihub repo when build for yourself...

**Comment by sseide** [comment]
The commit that removed the fix was reverted. Should be working again now.

Question remains why it is failing for some and not for others using same(?) docker image...

**Comment by sseide** [comment]
This problem should be fixed in current version. 
If you think its not feel free to reopen issue with updated informations based on latest version.
